- name: Orchestration Challenge Playbook
  hosts: ubuntu_servers
  become: true
  tasks:
    - name: Create a new user
      user:
        name: Jean
        group: sudo
        create_home: yes
 
    - name: Install Python (ensure it's installed)
      apt:
        name: python3
        state: present
        update_cache: yes
 
    - name: Install Python package management software (pip)
      apt:
        name: python3-pip
        state: present
 
    - name: Limit ports to only allow Python code API ports and SSH
      ufw:
        rule: allow
        port: ['22', '8000']
        state: enabled
 
    - name: Copy Python code to host
      copy:
        src: "/home/rm/Arbitr-Orchestration/Host/arbitr_devops/Orchestration Challenge/Code"
        dest: /home/Jean/python_code/
        owner: Jean
        group: Jean
        mode: '0755'
 
    - name: Install Python dependencies from requirements.txt
      pip:
        requirements: /home/Jean/python_code/requirements.txt
        executable: python3 -m pip
 
    - name: Run Python script within the context of the newly created user
      become: yes
      become_user: Jean
      command: /usr/bin/python3 -m uvicorn main:app --host 0.0.0.0 --port 8000
      args:
        chdir: /home/Jean/python_code/
 
    - name: Ensure Uvicorn service is running (optional, requires a systemd service setup)
      systemd:
        name: uvicorn
        state: started
        enabled: yes
        daemon_reload: yes
